apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: operator-build-controller-leader-election
rules:
  - apiGroups: ['']
    resources: ['configmaps']
    verbs: ['get', 'create', 'update']
  - apiGroups: ['']
    resources: ['events']
    verbs: ['create']
