apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: operator-build-controller-leader-election
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: operator-build-controller-leader-election
subjects:
- kind: ServiceAccount
  name: operator
  namespace: system
